# Generated by Django 4.2.20 on 2025-04-16 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
                ('category', models.CharField(choices=[('bills', 'Bills'), ('groceries', 'Groceries'), ('shopping', 'Shopping'), ('savings', 'Savings'), ('health_beauty', 'Health & Beauty'), ('holiday', 'Holiday'), ('entertainment', 'Entertainment'), ('car_travel', 'Car & Travel'), ('household_items', 'Household Items'), ('pets', 'Pets')], default='misc', max_length=50)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='budget.budget')),
            ],
        ),
    ]
